import os

CAFES = [
    {
        "name": "더티트렁크",
        "exactAddress": "경기 파주시 지목로 114",
        "ambiance": "공장형 빈티지, 압도적인 규모의 인생샷 포토존, 왁자지껄한 분위기",
        "signatureMenu": "더티블랙라떼, 내슈빌 치킨버거",
        "menuFeatures": "자극적이고 풍성한 비주얼의 미국식 브런치와 거친 텍스처의 시그니처 커피",
        "positiveReviews": "공간이 주는 압도감이 엄청납니다|어디서 찍어도 사진이 잘 나와요|빵과 브런치 양이 푸짐해요",
        "negativeReview": "주말에는 사람이 너무 많아서 대화하기 힘들 정도로 시끄럽습니다.",
        "reviewLinks": "https://blog.naver.com/dirty|https://youtube.com/dirty",
        "waitingSystem": "주말 피크타임 자리 눈치게임 필수",
        "hasPlugs": "False",
        "parkingInfo": "전용 대형 주차장 완비 (주차 요원 안내)",
        "hasDecaf": "True",
        "isLargeCafe": "True",
        "isPetFriendly": "False",
        "comparisons": ""
    },
    {
        "name": "테라로사 서종점",
        "exactAddress": "경기 양평군 서종면 북한강로 992",
        "ambiance": "북한강 뷰, 높은 층고와 붉은 벽돌의 따뜻한 분위기, 핸드드립 전문",
        "signatureMenu": "오늘의 드립커피, 까눌레",
        "menuFeatures": "다양한 산지의 스페셜티 원두를 직접 로스팅하여 신선한 드립 커피 제공",
        "positiveReviews": "커피 맛은 의심할 여지가 없습니다|계단식 좌석에서 책 읽기 좋아요|드라이브 코스로 완벽합니다",
        "negativeReview": "유명세만큼 주말 주차 진입이 상당히 오래 걸립니다.",
        "reviewLinks": "https://blog.naver.com/terarosa",
        "waitingSystem": "대기표 발권 후 웨이팅 (주말 30분 이상)",
        "hasPlugs": "False",
        "parkingInfo": "제1~3 전용 주차장 구비",
        "hasDecaf": "True",
        "isLargeCafe": "True",
        "isPetFriendly": "True",
        "comparisons": "나인블럭|커피 맛|테라로사 쪽이 산미 있는 스페셜티 원두 라인업이 훨씬 다양함"
    },
    {
        "name": "앤트러사이트 합정",
        "exactAddress": "서울 마포구 토정로5길 10",
        "ambiance": "폐공장을 개조한 인더스트리얼 인테리어, 집중하기 좋은 약간의 어두움",
        "signatureMenu": "나쓰메 소세키 (블렌드), 버터 팻 트리오",
        "menuFeatures": "묵직하고 다크한 원두부터 산뜻한 과일향까지 문학 작가 이름의 블렌딩 원두",
        "positiveReviews": "노트북 작업하거나 책 읽기 최고의 분위기|공간이 넓고 좌석 간격이 넉넉합니다|커피 향이 공간을 가득 채워요",
        "negativeReview": "의자와 테이블 높낮이가 안 맞는 자리가 많아 오래 앉아있기 불편합니다.",
        "reviewLinks": "https://youtube.com/anthracite",
        "waitingSystem": "주말 오후 시간대 일시적 만석",
        "hasPlugs": "True",
        "parkingInfo": "매장 앞 3~4대 협소 (인근 공영주차장 이용 권장)",
        "hasDecaf": "True",
        "isLargeCafe": "False",
        "isPetFriendly": "False",
        "comparisons": ""
    },
    {
        "name": "카멜커피 도산",
        "exactAddress": "서울 강남구 도산대로45길 16-8",
        "ambiance": "유럽 빈티지 감성, 아담하고 따뜻한 색감, 인스타그래머블",
        "signatureMenu": "카멜커피(아인슈패너), 앙버터",
        "menuFeatures": "진한 에스프레소 위에 달콤하고 쫀쫀한 우유 크림이 올라간 시그니처 크림 커피",
        "positiveReviews": "크림과 커피의 밸런스가 기가 막힙니다|매장 곳곳의 빈티지 가구들이 너무 예뻐요|앙버터 빵이 바삭하고 버터 풍미가 좋아요",
        "negativeReview": "매장이 좁고 대기가 너무 길어서 여유롭게 즐기기 어렵습니다.",
        "reviewLinks": "https://blog.naver.com/camel",
        "waitingSystem": "테이블링 원격 줄서기 필수 (대기 1~2시간)",
        "hasPlugs": "False",
        "parkingInfo": "발렛파킹 가능",
        "hasDecaf": "False",
        "isLargeCafe": "False",
        "isPetFriendly": "True",
        "comparisons": "하프커피|크림 텍스처|하프커피(버터크림)보다 카멜커피가 조금 더 묽고 커피향이 진함"
    },
    {
        "name": "모아니",
        "exactAddress": "경기 성남시 분당구 윷골길 116",
        "ambiance": "산자락에 위치한 자연 친화적 뷰, 통창, 깔끔하고 모던한 건축물",
        "signatureMenu": "바닐라 빈 라떼, 소금빵",
        "menuFeatures": "수제 바닐라 빈 시럽을 사용해 고급스러운 단맛을 낸 라떼와 담백한 베이커리",
        "positiveReviews": "숲 속에 온 듯한 뷰가 힐링 그 자체입니다|건축물이 갤러리처럼 아름다워요|테라스석 분위기가 최고입니다",
        "negativeReview": "산길을 꽤 올라가야 하고, 가격대가 전반적으로 매우 높습니다. (노키즈존 운영)",
        "reviewLinks": "https://youtube.com/moani",
        "waitingSystem": "주말 웨이팅 시스템 등록",
        "hasPlugs": "False",
        "parkingInfo": "자체 주차장 (결제 금액에 따라 무료 시간 다름)",
        "hasDecaf": "True",
        "isLargeCafe": "True",
        "isPetFriendly": "False",
        "comparisons": ""
    },
    {
        "name": "카페 진정성 본점",
        "exactAddress": "경기 김포시 하성면 하성로 660",
        "ambiance": "모던하고 미니멀한 건축물, 잔디밭, 통창 너머 한적한 풍경",
        "signatureMenu": "오리지널 골드 밀크티, 티라미수",
        "menuFeatures": "홍차잎을 100% 우유로 냉침해 끓여낸 묵직하고 덜 단 진짜 밀크티",
        "positiveReviews": "밀크티의 깊은 맛은 여기가 전국 1등입니다|공간이 넓고 자연과 어우러져 여유롭습니다|병 밀크티 포장해가기 좋아요",
        "negativeReview": "대중교통으로 접근이 불가능에 가까운 위치입니다.",
        "reviewLinks": "https://blog.naver.com/jinjung",
        "waitingSystem": "테이크아웃은 바로 가능, 착석은 눈치게임",
        "hasPlugs": "False",
        "parkingInfo": "제1~2 주차장 완비 (주차 공간 넉넉함)",
        "hasDecaf": "False",
        "isLargeCafe": "True",
        "isPetFriendly": "False",
        "comparisons": "클로리스|밀크티 맛|클로리스보다 단맛이 적고 우유의 묵직함이 강함"
    },
    {
        "name": "블루보틀 성수",
        "exactAddress": "서울 성동구 아차산로 7",
        "ambiance": "노출 콘크리트 미니멀리즘, 채광이 좋은 통창, 바리스타와 소통하는 열린 바",
        "signatureMenu": "놀라 플로트 (아이스크림 커피), 드립 커피",
        "menuFeatures": "유기농 우유 아이스크림을 올린 뉴올리언스 스타일 아이스 커피",
        "positiveReviews": "커피 맛이 아주 부드럽고 깔끔합니다|굿즈(MD)가 너무 예뻐서 사고 싶어져요|바리스타분들이 아주 친절합니다",
        "negativeReview": "의자가 딱딱하고 등받이가 없어 오래 앉아있기 힘든 디자인입니다.",
        "reviewLinks": "https://youtube.com/bluebottle",
        "waitingSystem": "오픈 직후 제외하면 웨이팅 거의 없음",
        "hasPlugs": "False",
        "parkingInfo": "주차 불가 (인근 유료주차장 이용)",
        "hasDecaf": "True",
        "isLargeCafe": "False",
        "isPetFriendly": "True",
        "comparisons": ""
    },
    {
        "name": "카페 레이어드 안국",
        "exactAddress": "서울 종로구 북촌로2길 2-3",
        "ambiance": "영국식 스콘과 케이크가 쌓여있는 엔틱 감성, 한옥 천장을 살린 인테리어",
        "signatureMenu": "크랜베리 크림치즈 스콘, 얼그레이 밀크티",
        "menuFeatures": "묵직하고 버터 향이 강한 영국식 투박한 스콘과 진한 크림 케이크들",
        "positiveReviews": "스콘 종류가 정말 다양하고 맛있습니다|영국 가정집 분위기가 물씬 납니다|한옥과 유럽 감성의 조화가 독특해요",
        "negativeReview": "매장이 협소하고 좌석이 다닥다닥 붙어있어 쾌적하지 않습니다.",
        "reviewLinks": "https://blog.naver.com/layered",
        "waitingSystem": "상시 웨이팅 (캐치테이블/테이블링 없음, 현장 대기)",
        "hasPlugs": "False",
        "parkingInfo": "주차 불가",
        "hasDecaf": "False",
        "isLargeCafe": "False",
        "isPetFriendly": "False",
        "comparisons": "스코프|스콘 식감|레이어드 스콘이 좀 더 부드럽고 수분감이 있는 편"
    },
    {
        "name": "나인블럭 기흥점",
        "exactAddress": "경기 용인시 기흥구 공세로 34",
        "ambiance": "어둡고 넓은 인더스트리얼 창고형, 가죽 쇼파, 웅장한 사운드",
        "signatureMenu": "나인블럭 블렌드 아메리카노, 몽블랑 페이스트리",
        "menuFeatures": "산미를 줄이고 고소함과 바디감을 강조한 다크 로스팅 커피",
        "positiveReviews": "테이블이 큼직하고 소파가 편안해 작업하거나 대화하기 좋습니다|주차가 매우 편합니다|빵 퀄리티도 준수해요",
        "negativeReview": "커피와 베이커리 가격이 다소 비싼 편입니다.",
        "reviewLinks": "https://youtube.com/9block",
        "waitingSystem": "매장이 커서 대기 거의 없음",
        "hasPlugs": "True",
        "parkingInfo": "전용 대형 주차장 완비 (무료)",
        "hasDecaf": "True",
        "isLargeCafe": "True",
        "isPetFriendly": "False",
        "comparisons": ""
    },
    {
        "name": "나무사이로",
        "exactAddress": "서울 종로구 사직로8길 21",
        "ambiance": "전통 한옥의 고즈넉함과 서까래, 중정이 있는 차분한 분위기",
        "signatureMenu": "디카페인 아메리카노(풍선껌 향), 드립 커피",
        "menuFeatures": "국내 1세대 스페셜티 로스터리의 철학이 담긴 화사하고 다채로운 원두 라인업",
        "positiveReviews": "디카페인 커피 중 가장 향긋하고 맛있습니다|비 오는 날 한옥 마루에서 마시는 커피가 예술입니다|혼자 조용히 머물기 좋아요",
        "negativeReview": "골목 안쪽에 있어 처음 찾아갈 때 헤맬 수 있습니다.",
        "reviewLinks": "https://blog.naver.com/namusairo",
        "waitingSystem": "주말 만석 시 현장 대기",
        "hasPlugs": "True",
        "parkingInfo": "주차 불가",
        "hasDecaf": "True",
        "isLargeCafe": "False",
        "isPetFriendly": "True",
        "comparisons": ""
    },
    {
        "name": "프로퍼커피바",
        "exactAddress": "서울 송파구 위례성대로22길 6",
        "ambiance": "동네 주민들이 사랑하는 힙하고 활기찬 우드톤 공간",
        "signatureMenu": "헤이즐넛 라떼, 피스타치오 크루아상",
        "menuFeatures": "기분 좋게 달콤한 시럽과 진한 샷의 조화, 수준 높은 페이스트리 베이커리",
        "positiveReviews": "동네 카페 퀄리티를 넘어선 커피와 빵 맛입니다|라떼 폼이 정말 부드러워요|채광이 좋아 사진이 따뜻하게 나옵니다",
        "negativeReview": "매장이 울리는 구조라 대화 소리가 다소 웅성웅성 들립니다.",
        "reviewLinks": "https://youtube.com/proper",
        "waitingSystem": "주말 웨이팅 리스트 수기 작성",
        "hasPlugs": "False",
        "parkingInfo": "매장 앞 2~3대 가능 (협소)",
        "hasDecaf": "True",
        "isLargeCafe": "False",
        "isPetFriendly": "True",
        "comparisons": ""
    },
    {
        "name": "어니언 안국",
        "exactAddress": "서울 종로구 계동길 5",
        "ambiance": "거대한 한옥 저택 개조, 마당과 대청마루, 한국적 인스타 감성",
        "signatureMenu": "팡도르, 플랫화이트",
        "menuFeatures": "슈가파우더가 산더미처럼 쌓인 폭신한 팡도르와 고소한 플랫화이트",
        "positiveReviews": "외국인 친구 데려가면 무조건 환호하는 곳입니다|한옥 대청마루 좌식 자리가 운치 있어요|빵 종류가 굉장히 많습니다",
        "negativeReview": "야외 좌석은 여름에 덥고 벌레가, 겨울엔 추워서 이용이 힘듭니다.",
        "reviewLinks": "https://blog.naver.com/onion",
        "waitingSystem": "입장 대기줄 상시 존재 (평일 포함)",
        "hasPlugs": "False",
        "parkingInfo": "현대계동사옥 유료주차장 이용 권장",
        "hasDecaf": "True",
        "isLargeCafe": "False",
        "isPetFriendly": "False",
        "comparisons": ""
    },
    {
        "name": "포레스트아웃팅스",
        "exactAddress": "경기 고양시 일산동구 고양대로 1124",
        "ambiance": "실내 식물원 컨셉, 분수대와 정원, 웅장하고 거대한 층고",
        "signatureMenu": "아메리카노, 시즌 생과일 크로아상",
        "menuFeatures": "대중적인 맛의 원두 2종 선택 가능, 크고 화려한 비주얼의 베이커리류",
        "positiveReviews": "실내 식물원에 온 것처럼 초록초록해서 부모님 모시고 가기 좋아요|날씨 상관없이 기분 전환하기 최고입니다|좌석이 다양해서 골라 앉는 재미가 있어요",
        "negativeReview": "음료와 빵 가격이 뷰티켓 값이라 생각해야 할 정도로 비쌉니다.",
        "reviewLinks": "https://youtube.com/forest",
        "waitingSystem": "규모가 워낙 커서 자리는 어떻게든 남 (주차는 대기 필요)",
        "hasPlugs": "False",
        "parkingInfo": "초대형 지하/지상 주차장 완비 (안내요원 다수)",
        "hasDecaf": "True",
        "isLargeCafe": "True",
        "isPetFriendly": "False",
        "comparisons": "더티트렁크|분위기|더티트렁크가 어둡고 빈티지하다면, 포레스트아웃팅스는 밝고 싱그러운 느낌"
    },
    {
        "name": "마일스톤 커피",
        "exactAddress": "서울 강남구 논현로153길 46",
        "ambiance": "호주 멜버른 스타일의 캐주얼하고 힙한 분위기, 테라스",
        "signatureMenu": "호주식 카푸치노, 플랫화이트, 티라미수",
        "menuFeatures": "코코아 파우더가 듬뿍 올라간 쫀득한 거품의 카푸치노와 수제 마스카포네 티라미수",
        "positiveReviews": "커피와 티라미수 조합이 환상적입니다|직원분들이 매우매우 친절하고 에너지가 넘쳐요|호주에 온 것 같은 자유로운 분위기입니다",
        "negativeReview": "좌석이 많지 않아 평일 애매한 시간에도 웨이팅이 있습니다.",
        "reviewLinks": "https://blog.naver.com/milestone",
        "waitingSystem": "웨이팅 패드 입력 (알림톡)",
        "hasPlugs": "False",
        "parkingInfo": "발렛파킹 가능",
        "hasDecaf": "True",
        "isLargeCafe": "False",
        "isPetFriendly": "True",
        "comparisons": ""
    },
    {
        "name": "프릳츠 마포점",
        "exactAddress": "서울 마포구 새창로2길 17",
        "ambiance": "레트로 빈티지 코리안 감성, 어두운 조명과 자개장, 마당",
        "signatureMenu": "잘되어가시나(원두) 브루잉 커피, 크루아상",
        "menuFeatures": "단맛을 바탕으로 한 훌륭한 밸런스의 블렌딩 원두와 클래식하고 바삭한 프렌치 베이커리",
        "positiveReviews": "원두를 사가고 싶을 정도로 커피 맛이 뛰어납니다|레트로 감성의 물개 캐릭터 굿즈가 매력적이에요|크루아상이 결대로 바삭하게 찢어집니다",
        "negativeReview": "매장 내부가 다소 어둡고 계단이 가파릅니다.",
        "reviewLinks": "https://youtube.com/fritz",
        "waitingSystem": "빵 결제 줄과 착석 눈치게임 병행",
        "hasPlugs": "True",
        "parkingInfo": "주차 불가 (도화공영주차장 이용)",
        "hasDecaf": "True",
        "isLargeCafe": "False",
        "isPetFriendly": "False",
        "comparisons": ""
    },
    {
        "name": "어니언 성수",
        "exactAddress": "서울 성동구 아차산로9길 8",
        "ambiance": "낡은 공장과 인더스트리얼의 극치, 러프하고 빈티지한 분위기",
        "signatureMenu": "팡도르, 아메리카노",
        "menuFeatures": "폐공장을 개조한 공간에서 즐기는 달콤한 베이커리와 고소한 커피",
        "positiveReviews": "성수동 감성의 끝판왕입니다|옥상 테라스석 분위기가 너무 좋아요|빵 종류가 다양합니다",
        "negativeReview": "테이블이 낮아 먹기 불편하고 의자가 딱딱합니다.",
        "reviewLinks": "https://blog.naver.com/onion_seongsu|https://youtube.com/onion",
        "waitingSystem": "주말 상시 웨이팅",
        "hasPlugs": "False",
        "parkingInfo": "주차 불가 (근처 공영주차장)",
        "hasDecaf": "False",
        "isLargeCafe": "True",
        "isPetFriendly": "False",
        "comparisons": "대림창고|인더스트리얼 감성|어니언 성수가 대림창고보다 베이커리 종류가 훨씬 다양하고 야외 마당이 넓음"
    },
    {
        "name": "센터커피 성수점",
        "exactAddress": "서울 성동구 서울숲2길 28-11",
        "ambiance": "서울숲 뷰, 평화롭고 조용한 숲속 감성",
        "signatureMenu": "게이샤 드립커피",
        "menuFeatures": "영국 바리스타 챔피언이 큐레이션한 하이엔드 스페셜티 커피",
        "positiveReviews": "커피 맛이 정말 깔끔하고 향긋합니다|서울숲을 보며 멍때리기 가장 좋은 곳|디저트도 훌륭해요",
        "negativeReview": "매장이 작아 자리 잡기가 매우 힙듭니다.",
        "reviewLinks": "https://youtube.com/centercoffee",
        "waitingSystem": "오후 시간대 만석",
        "hasPlugs": "False",
        "parkingInfo": "주차 불가 (서울숲 주차장 이용)",
        "hasDecaf": "True",
        "isLargeCafe": "False",
        "isPetFriendly": "True",
        "comparisons": "메쉬커피|커피 산미|센터커피가 메쉬커피보다 좀 더 화사하고 산뜻한 과일향에 집중함"
    },
    {
        "name": "딩가케이크",
        "exactAddress": "서울 마포구 동교로29길 68",
        "ambiance": "미국 레트로 하이틴 영화 세트장 같은 빈티지 팝 감성",
        "signatureMenu": "얼그레이 케이크, 레드벨벳 케이크",
        "menuFeatures": "장난감같이 귀여운 비주얼의 꾸덕하고 진한 레터링 케이크들",
        "positiveReviews": "케이크 비주얼이 너무 예뻐서 사진 찍기 바쁩니다|인테리어가 동화 같아요|얼그레이 향이 진해서 맛있습니다",
        "negativeReview": "미국식 케이크라 단맛이 매우 강해 호불호가 갈립니다.",
        "reviewLinks": "https://blog.naver.com/dingacake",
        "waitingSystem": "주말 오후 웨이팅 필수",
        "hasPlugs": "False",
        "parkingInfo": "주차 불가",
        "hasDecaf": "False",
        "isLargeCafe": "False",
        "isPetFriendly": "True",
        "comparisons": "하이웨스트|디저트 비주얼|하이웨스트가 빈티지 스콘 중심이라면, 딩가케이크는 미국 하이틴 감성의 레터링 케이크 중심"
    },
    {
        "name": "카페 공명",
        "exactAddress": "서울 마포구 연희로 11",
        "ambiance": "출판사에서 운영하는 차분하고 넓은 북카페 느낌",
        "signatureMenu": "공명밀크티, 우유생크림 스콘",
        "menuFeatures": "필름 카메라와 책이 어우러진 공간에서 즐기는 달콤한 스콘",
        "positiveReviews": "노트북 켜고 작업하기 최고의 환경입니다|밀크티 보틀이 예뻐요|스콘 안에 크림이 듬뿍 들어있습니다",
        "negativeReview": "카공족이 많아 자리가 잘 나지 않습니다.",
        "reviewLinks": "https://youtube.com/cafegongmyoung",
        "waitingSystem": "만석 시 웨이팅 (회전율 낮음)",
        "hasPlugs": "True",
        "parkingInfo": "주차 불가",
        "hasDecaf": "False",
        "isLargeCafe": "True",
        "isPetFriendly": "False",
        "comparisons": "테일러커피|작업 환경|공명이 테일러커피 연남점보다 층고가 높고 콘센트석이 많아 작업하기 더 편함"
    },
    {
        "name": "맥심플랜트",
        "exactAddress": "서울 용산구 이태원로 250",
        "ambiance": "통창 뷰, 도심 속 거대한 라이브러리 같은 세련된 복합 공간",
        "signatureMenu": "맥심 모카골드 라떼, 스페셜티 드립",
        "menuFeatures": "우리가 아는 믹스커피의 하이엔드 버전과 최고급 원두의 드립 커피",
        "positiveReviews": "대기업의 자본력이 느껴지는 압도적인 공간입니다|콘센트가 많아 작업하기 좋습니다|층마다 다른 컨셉이 재미있어요",
        "negativeReview": "워낙 사람이 많아서 조용한 분위기를 기대하긴 어렵습니다.",
        "reviewLinks": "https://blog.naver.com/maximplant",
        "waitingSystem": "규모가 커서 자리는 금방 남",
        "hasPlugs": "True",
        "parkingInfo": "지하 주차장 (협소)",
        "hasDecaf": "True",
        "isLargeCafe": "True",
        "isPetFriendly": "False",
        "comparisons": "스타벅스 리저브 한남|공간 쾌적성|스타벅스보다 맥심플랜트가 좌석 간격이 더 넓고 라이브러리 존이 분리되어 있어 조용함"
    },
    {
        "name": "새들러하우스",
        "exactAddress": "서울 강남구 도산대로17길 10",
        "ambiance": "아늑하고 유럽 지하 와인바 같은 포근한 분위기",
        "signatureMenu": "프렌치 와플(크로플)",
        "menuFeatures": "겉바속촉의 정석, 한국 크로플 열풍을 이끈 버터 풍미 가득한 크로플",
        "positiveReviews": "인생 크로플입니다. 무조건 드세요|바질 크로플의 단짠 조합이 미쳤습니다|선물 포장용으로도 아주 좋아요",
        "negativeReview": "매장 취식보다 포장 대기가 더 길 때가 많습니다.",
        "reviewLinks": "https://youtube.com/saddlerhaus",
        "waitingSystem": "포장/취식 모두 웨이팅 필수",
        "hasPlugs": "False",
        "parkingInfo": "발렛파킹 가능",
        "hasDecaf": "False",
        "isLargeCafe": "False",
        "isPetFriendly": "True",
        "comparisons": "아우프글렛|크로플 식감|아우프글렛이 아이스크림과의 조화를 중시한다면, 새들러하우스는 크로플 자체의 바삭함과 코팅(바질 등)에 집중함"
    },
    {
        "name": "스타벅스 더양평DTR점",
        "exactAddress": "경기 양평군 양평읍 양근로 76",
        "ambiance": "국내 최대 규모 스벅, 남한강이 한눈에 보이는 리저브 전용 뷰",
        "signatureMenu": "리저브 콜드브루, 매장에서 직접 굽는 빵",
        "menuFeatures": "일반 스벅에 없는 양평 전용 베이커리와 프리미엄 리저브 커피",
        "positiveReviews": "강을 바라보며 마시는 커피가 힐링입니다|규모가 커서 구경하는 재미가 있어요|직접 굽는 빵 퀄리티가 스벅 이상입니다",
        "negativeReview": "주말엔 시장통을 방불케 할 정도로 사람이 미어터집니다.",
        "reviewLinks": "https://blog.naver.com/starbucksdtr",
        "waitingSystem": "주문 대기 30분, 자리 잡기 눈치게임",
        "hasPlugs": "True",
        "parkingInfo": "전용 주차장 (혼잡)",
        "hasDecaf": "True",
        "isLargeCafe": "True",
        "isPetFriendly": "False",
        "comparisons": "스타벅스 리버사이드팔당DTR|뷰와 규모|양평DTR이 팔당DTR보다 매장 규모와 베이커리 메뉴 라인업이 훨씬 압도적임"
    },
    {
        "name": "요새 (YOSE)",
        "exactAddress": "경기 남양주시 와부읍 경강로926번길 38",
        "ambiance": "한강을 마주보는 하얀색 2층 저택, 테라스석의 여유로움",
        "signatureMenu": "요새 시그니처 햄버거, 자몽에이드",
        "menuFeatures": "커피뿐 아니라 수제 버거와 샐러드가 맛있는 브런치 맛집",
        "positiveReviews": "테라스에서 보는 한강 일몰이 예술입니다|수제버거가 정말 맛있어요|드라이브하다 들르기 딱 좋은 위치입니다",
        "negativeReview": "강변이라 저녁이 되면 날벌레가 좀 있습니다.",
        "reviewLinks": "https://youtube.com/yose",
        "waitingSystem": "야외 명당 자리는 치열함",
        "hasPlugs": "False",
        "parkingInfo": "전용 주차장",
        "hasDecaf": "False",
        "isLargeCafe": "True",
        "isPetFriendly": "False",
        "comparisons": "나인블럭 뷰 팔당점|테라스 뷰|요새가 나인블럭보다 한강과 더 가깝게 닿아있어 야외 정원 느낌이 강함"
    },
    {
        "name": "말똥도넛 디저트타운",
        "exactAddress": "경기 파주시 지목로 137",
        "ambiance": "미국 서부 LA 놀이공원 컨셉, 화려한 네온사인과 핑크빛 인테리어",
        "signatureMenu": "말똥 오리지널 도넛, 말똥 젤라또",
        "menuFeatures": "당이 폭발할 것 같은 알록달록한 아메리칸 스타일 도넛과 젤라또",
        "positiveReviews": "사진이 진짜 잘 나와서 인스타용으로 최고입니다|도넛 비주얼이 화려해요|아이들이 너무 좋아합니다",
        "negativeReview": "도넛이 너무 달아서 많이 먹기 힘들고, 줄이 너무 깁니다.",
        "reviewLinks": "https://blog.naver.com/malddong",
        "waitingSystem": "주말 웨이팅 1시간 이상",
        "hasPlugs": "False",
        "parkingInfo": "전용 대형 주차장 (안내원 있음)",
        "hasDecaf": "False",
        "isLargeCafe": "True",
        "isPetFriendly": "False",
        "comparisons": "노티드|도넛 스타일|노티드가 부드러운 우유크림이라면 말똥도넛은 화려한 글레이징과 토핑 위주"
    },
    {
        "name": "비루개",
        "exactAddress": "경기 남양주시 별내면 용암비루개길 219-88",
        "ambiance": "산꼭대기에 위치한 대형 온실 식물원, 해먹과 텐트 좌석",
        "signatureMenu": "아메리카노, 구워먹는 소시지와 가래떡",
        "menuFeatures": "산속 식물원에서 캠핑하듯 모닥불에 직접 구워먹는 주전부리",
        "positiveReviews": "진짜 산속 깊은 곳이라 공기가 다릅니다|해먹 자리가 너무 편해서 잠이 와요|별 보러 가기 좋은 카페입니다",
        "negativeReview": "올라가는 길이 매우 가파르고 좁아서 초보운전은 위험합니다.",
        "reviewLinks": "https://youtube.com/birugae",
        "waitingSystem": "해먹 자리는 현장 예약 필수",
        "hasPlugs": "False",
        "parkingInfo": "대형 주차장 완비",
        "hasDecaf": "False",
        "isLargeCafe": "True",
        "isPetFriendly": "False",
        "comparisons": "식물관PH|식물원 컨셉|식물관PH가 모던한 갤러리 느낌이라면 비루개는 거대한 야외 산장 느낌이 강함"
    },
    {
        "name": "카페 노티드 청담",
        "exactAddress": "서울 강남구 도산대로53길 15",
        "ambiance": "스마일 캐릭터와 파스텔톤의 귀엽고 아기자기한 감성",
        "signatureMenu": "우유 생크림 도넛, 바닐라 도넛",
        "menuFeatures": "입에서 사르르 녹는 폭신한 빵과 느끼하지 않은 우유 생크림의 환상 조화",
        "positiveReviews": "아무리 먹어도 질리지 않는 덜 단 크림이 일품입니다|패키지가 예뻐서 선물용으로 최고|매장 곳곳이 포토존입니다",
        "negativeReview": "매장 취식보다 포장 손님이 많아 어수선합니다.",
        "reviewLinks": "https://blog.naver.com/knotted_cheongdam",
        "waitingSystem": "포장 줄 상시 대기 (앱 예약 권장)",
        "hasPlugs": "False",
        "parkingInfo": "발렛파킹",
        "hasDecaf": "False",
        "isLargeCafe": "False",
        "isPetFriendly": "False",
        "comparisons": "랜디스도넛|식감|랜디스는 쫀득하고 묵직한 미국식 식감, 노티드는 폭신하고 가벼운 한국식 생크림 식감"
    },
    {
        "name": "정지영커피로스터즈 장안문점",
        "exactAddress": "경기 수원시 팔달구 신풍로 42",
        "ambiance": "수원 화성 성곽이 바로 보이는 루프탑 뷰, 빈티지한 구옥 개조",
        "signatureMenu": "코코넛 로스터리 라떼, 크루아상",
        "menuFeatures": "직접 로스팅한 신선한 원두와 달콤고소한 코코넛 라떼의 조화",
        "positiveReviews": "루프탑에서 성곽 보며 마시는 커피가 기가 막힙니다|수원 행궁동 감성의 원조격입니다|노을 질 때 뷰가 환상적이에요",
        "negativeReview": "계단이 가파르고 노키즈존으로 운영됩니다.",
        "reviewLinks": "https://youtube.com/jungjiyoung",
        "waitingSystem": "주말 명당 자리 경쟁 치열",
        "hasPlugs": "False",
        "parkingInfo": "주차 불가 (인근 화성행궁 공영주차장)",
        "hasDecaf": "False",
        "isLargeCafe": "False",
        "isPetFriendly": "False",
        "comparisons": "킵댓|로스터리|킵댓이 에스프레소 베이스의 크림 커피에 강하다면, 정지영커피는 코코넛 등 다채로운 시그니처 배리에이션에 강함"
    },
    {
        "name": "카페 뮬라",
        "exactAddress": "서울 강남구 압구정로4길 13-12",
        "ambiance": "유리 온실 컨셉의 화이트 톤 대형 카페, 햇살 가득한 채광",
        "signatureMenu": "대왕 티라미수, 뮬라 그린티 밀크",
        "menuFeatures": "벽돌 크기의 압도적인 대왕 티라미수와 싱그러운 녹차 음료",
        "positiveReviews": "사진이 정말 밝고 화사하게 나옵니다|티라미수 양이 어마어마해서 돈이 아깝지 않아요|도심 속 온실이라 힐링됩니다",
        "negativeReview": "유리 온실이라 한여름 낮에는 에어컨을 틀어도 다소 덥습니다.",
        "reviewLinks": "https://blog.naver.com/cafemula",
        "waitingSystem": "주말 오후 대기 발생",
        "hasPlugs": "False",
        "parkingInfo": "발렛파킹",
        "hasDecaf": "False",
        "isLargeCafe": "False",
        "isPetFriendly": "True",
        "comparisons": "식물학|그린테리어|식물학이 도심 속 작은 식물원이라면 뮬라는 거대한 대저택 온실 느낌"
    },
    {
        "name": "도토리 가든",
        "exactAddress": "서울 종로구 계동길 19-8",
        "ambiance": "스튜디오 지브리 애니메이션에 들어온 듯한 신비로운 폐가 컨셉",
        "signatureMenu": "도토리빵, 그릭 요거트",
        "menuFeatures": "도토리 모양을 한 귀여운 마들렌과 꾸덕한 수제 그릭 요거트볼",
        "positiveReviews": "외관부터 내부까지 동화 속에 들어온 기분입니다|그릭 요거트가 정말 꾸덕하고 신선해요|굿즈들이 너무 귀엽습니다",
        "negativeReview": "공간이 미로 같고 계단이 많아 조금 위험할 수 있습니다.",
        "reviewLinks": "https://youtube.com/dotorigarden",
        "waitingSystem": "입장부터 줄 서서 빵 고르는 시스템",
        "hasPlugs": "False",
        "parkingInfo": "주차 불가",
        "hasDecaf": "False",
        "isLargeCafe": "False",
        "isPetFriendly": "False",
        "comparisons": "런던베이글뮤지엄|세계관 몰입도|런던베이글이 영국을 구현했다면, 도토리가든은 지브리 감성의 숲속 오두막을 완벽히 구현함"
    },
    {
        "name": "마하 한남",
        "exactAddress": "서울 용산구 무지개아파트 상가 4층",
        "ambiance": "한강과 도심이 파노라마로 펼쳐지는 모던하고 차분한 건축 작업실 느낌",
        "signatureMenu": "마하 블렌드 커피, 치즈 케이크",
        "menuFeatures": "건축가 최동규의 작업실을 개조해 만든 묵직하고 깊은 맛의 핸드드립 전용 카페",
        "positiveReviews": "통창으로 보이는 한강 야경이 최고입니다|음악과 공간의 울림이 좋아서 혼자 사색하기 완벽해요|커피 향이 아주 깊습니다",
        "negativeReview": "오래된 아파트 상가라 화장실 등 부대시설이 열악합니다.",
        "reviewLinks": "https://blog.naver.com/machahannam",
        "waitingSystem": "조용한 분위기 유지를 위해 웨이팅 있음",
        "hasPlugs": "True",
        "parkingInfo": "주차 불가 (인근 공영주차장 도보 이동)",
        "hasDecaf": "False",
        "isLargeCafe": "False",
        "isPetFriendly": "False",
        "comparisons": "맥심플랜트|전망|맥심플랜트가 도심 한복판 뷰라면 마하 한남은 한강과 다리 야경이 파노라마로 펼쳐지는 뷰"
    }
]

def main():
    out_dir = "src/main/resources"
    os.makedirs(out_dir, exist_ok=True)
    out_file = os.path.join(out_dir, "cafes.tsv")

    with open(out_file, "w", encoding="utf-8") as f:
        header = [
            "name", "exactAddress", "ambiance", "signatureMenu", "menuFeatures",
            "positiveReviews", "negativeReview", "reviewLinks", "waitingSystem",
            "hasPlugs", "parkingInfo", "hasDecaf", "isLargeCafe", "isPetFriendly", "comparisons"
        ]
        f.write("\t".join(header) + "\n")
        
        for cafe in CAFES:
            row = [
                cafe["name"],
                cafe["exactAddress"],
                cafe["ambiance"],
                cafe["signatureMenu"],
                cafe["menuFeatures"],
                cafe["positiveReviews"],
                cafe["negativeReview"],
                cafe["reviewLinks"],
                cafe["waitingSystem"],
                cafe["hasPlugs"],
                cafe["parkingInfo"],
                cafe["hasDecaf"],
                cafe["isLargeCafe"],
                cafe["isPetFriendly"],
                cafe["comparisons"]
            ]
            f.write("\t".join(row) + "\n")

    print(f"Generated {out_file} with {len(CAFES)} cafes successfully.")

if __name__ == "__main__":
    main()
